// Expo config plugin that drops a Network Security Config into the Android
// resources and wires `android:networkSecurityConfig` on the application tag.
//
// Pinning strategy: we pin the **public-key (SPKI) hashes of Let's Encrypt
// intermediates** (E5–E8, R10, R11) plus the ISRG Root X1 root, scoped to the
// tenant's gateway + backend hostnames. We deliberately do NOT pin leaf certs —
// LE leaves rotate every ~90 days and pinning them would brick the app on
// every renewal. Pinning the intermediate chain blocks rogue-CA MITM attacks
// (corporate proxies, malware-installed roots, custom user CAs) while leaving
// LE's leaf-rotation cycle untouched.
//
// `expiration` is set ~12 months out so that, if the pin set drifts behind
// what LE actually serves, the app gracefully falls back to system trust
// after expiry rather than refusing all traffic. Bump the date on every
// build that updates pins; track LE intermediate rotations at
// https://letsencrypt.org/certificates/.
//
// If the tenant ever migrates off LE (private CA, DigiCert, etc.) the pin set
// must be regenerated for that issuer — the LE pins below will not match.
const { withAndroidManifest, withDangerousMod, AndroidConfig } = require('@expo/config-plugins');
const { writeFileSync, mkdirSync } = require('node:fs');
const { join } = require('node:path');

// ── Pin set ────────────────────────────────────────────────────────────────
// SHA-256 SPKI of every active Let's Encrypt intermediate + the ISRG Root X1.
// Generated 2026-04-26 from https://letsencrypt.org/certs/2024/<name>.pem.
const LE_INTERMEDIATE_PINS = [
  'NYbU7PBwV4y9J67c4guWTki8FJ+uudrXL0a4V4aRcrg=', // E5
  '0Bbh/jEZSKymTy3kTOhsmlHKBB32EDu1KojrP3YfV9c=', // E6
  'y7xVm0TVJNahMr2sZydE2jQH8SquXV9yLF9seROHHHU=', // E7 (current leaf signer for *.uril.rs)
  'iFvwVyJSxnQdyaUvUERIf+8qk7gRze3612JMwoO3zdU=', // E8
  'K7rZOrXHknnsEhUH8nLL4MZkejquUuIvOIr6tCa0rbo=', // R10
  'bdrBhpj38ffhxpubzkINl0rG+UyossdhcBYj+Zx2fcc=', // R11
  'C5+lpZ7tcVwmwQIMcRtPbsQtWLABXhQzejna0wHFr8M=', // ISRG Root X1
];

// Pin-set expiration. After this date Android stops enforcing the pins on
// non-user-installed CAs and falls back to system trust. Bump on every plugin
// edit; never set further than ~13 months out.
const PIN_EXPIRATION = '2027-04-26';

function hostnameOf(url) {
  try {
    return new URL(url).hostname;
  } catch (e) {
    throw new Error(`[withCertPinning] Invalid URL in tenant config: ${url}`);
  }
}

function buildXml(domains, pins, expiration) {
  const pinElements = pins
    .map((p) => `        <pin digest="SHA-256">${p}</pin>`)
    .join('\n');
  const domainElements = domains
    .map((d) => `    <domain includeSubdomains="false">${d}</domain>`)
    .join('\n');

  return `<?xml version="1.0" encoding="utf-8"?>
<!--
  AUTO-GENERATED by plugins/withCertPinning.js on every \`expo prebuild\`.
  Do not edit this file directly — your changes will be overwritten.
-->
<network-security-config>
  <!-- Tenant-pinned domains. All other traffic uses default system trust. -->
  <domain-config>
${domainElements}
    <pin-set expiration="${expiration}">
${pinElements}
    </pin-set>
  </domain-config>
  <!-- Default policy: HTTPS only (cleartext blocked) for every other host.
       Override is needed only for Metro dev server, which Expo handles
       separately via debug-only network config. -->
  <base-config cleartextTrafficPermitted="false">
    <trust-anchors>
      <certificates src="system" />
    </trust-anchors>
  </base-config>
</network-security-config>
`;
}

module.exports = function withCertPinning(config) {
  const tenant = config.extra?.tenant;
  if (!tenant?.gatewayUrl || !tenant?.backendUrl) {
    throw new Error('[withCertPinning] tenant.gatewayUrl + tenant.backendUrl required.');
  }

  const domains = Array.from(new Set([
    hostnameOf(tenant.gatewayUrl),
    hostnameOf(tenant.backendUrl),
  ]));

  // Step 1: drop network_security_config.xml into res/xml/
  config = withDangerousMod(config, [
    'android',
    async (cfg) => {
      const xmlDir = join(cfg.modRequest.platformProjectRoot, 'app/src/main/res/xml');
      mkdirSync(xmlDir, { recursive: true });
      const xml = buildXml(domains, LE_INTERMEDIATE_PINS, PIN_EXPIRATION);
      writeFileSync(join(xmlDir, 'network_security_config.xml'), xml);
      return cfg;
    },
  ]);

  // Step 2: reference it from the <application> tag
  config = withAndroidManifest(config, (cfg) => {
    const application = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults);
    application.$['android:networkSecurityConfig'] = '@xml/network_security_config';
    return cfg;
  });

  return config;
};
